use std::env;

fn main() {
    // libflite_uefi.a lives one directory up (uefi-port/), regenerated by
    // uefi-port/build-uefi-c.sh. Resolve relative to this crate so the link
    // works whether built directly or as a dependency of another crate.
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let dir = format!("{manifest}/..");
    println!("cargo:rustc-link-search=native={dir}");
    println!("cargo:rustc-link-lib=static=flite_uefi");
    println!("cargo:rerun-if-changed={dir}/libflite_uefi.a");
}
